type: "radar"
title: "Comparison of Dominik Szoboszlai and Martin Ødegaard (2024/2025)"
subtitle: "Various Metrics per Game"

# Each axis: name, min, max
indicators:
  - name: "Key Passes"
    min: 0
    max: 3
  - name: "Pass Completion Rate"
    min: 0
    max: 100
  - name: "Duels Won"
    min: 0
    max: 5
  - name: "Accurate Crosses"
    min: 0
    max: 1
  - name: "Successful Dribbles"
    min: 0
    max: 2
  - name: "Fouls Drawn"
    min: 0
    max: 2
  - name: "Goals"
    min: 0
    max: 5
  - name: "Assists"
    min: 0
    max: 5

# We can choose circle or polygon
radarShape: "polygon"

# Optional: define the ring colors for the background
ringColors:
  - "#2b2b2b"
  - "#3a3a3a"

datasets:
  - label: "Dominik Szoboszlai 2024/2025"
    values: [2.01, 86.38, 4.15, 0.69, 0.9, 0.83, 3, 2]
    lineColor: "rgba(255, 0, 0,1)"       # brighter outline color for polygon
    fillColor: "rgba(255, 0, 0,0.3)"     # dimmer inside fill
  - label: "Martin Ødegaard 2024/2025"
    values: [2.46, 87.91, 3.29, 0.82, 1.05, 1.05, 1, 3]
    lineColor: "rgba(0, 191, 255,1)"     # brighter outline color for polygon
    fillColor: "rgba(0, 191, 255,0.3)"   # dimmer inside fill