league: albania_superliga
league_name_pretty: 'Albanian Superliga'
predictions_pathways:
  Match_Result: /root/barnard/ML/Models/albania_superliga/Datasets/MR_2425_Prediction_Dataset.csv
  BTTS_FTS: /root/barnard/ML/Models/albania_superliga/Datasets/BTTS_FTS_2425_Prediction_Dataset.csv
  Clean_Sheet: /root/barnard/ML/Models/albania_superliga/Datasets/CS_2425_Prediction_Dataset.csv
training_model_pathways:
  Match_Result: /root/barnard/ML/Models/albania_superliga/Training-Results/Match-Result
  BTTS_FTS: /root/barnard/ML/Models/albania_superliga/Training-Results/BTTS-FTS
  Clean_Sheet: /root/barnard/ML/Models/albania_superliga/Training-Results/Clean-Sheet
prediction_metrics_pathway:
  Match_Result: /root/barnard/ML/Models/albania_superliga/Prediction-Results/Match-Result
  BTTS_FTS: /root/barnard/ML/Models/albania_superliga/Prediction-Results/BTTS-FTS
  Clean_Sheet: /root/barnard/ML/Models/albania_superliga/Prediction-Results/Clean-Sheet
prediction_model_pathway:
  Match_Result: "/root/barnard/ML/Models/combined_leagues/Training-Results/Match-Result/v6-ionised-ect-rs42/v6-ionised-ect-rs42.joblib"
  BTTS_FTS: ''
  Clean_Sheet: ''
training_dataset_pathway:
  Match_Result: /root/barnard/ML/Models/albania_superliga/Datasets/MR_Dataset.csv
  BTTS_FTS: /root/barnard/ML/Models/albania_superliga/Datasets/BTTS_FTS_Dataset.csv
  Clean_Sheet: /root/barnard/ML/Models/albania_superliga/Datasets/Clean_Sheet_Dataset.csv
country: ALB
league_type: domestic
domestic_value: 1
competition_ids:
  2013/2014:  301
  2014/2015:  300
  2015/2016:  331
  2016/2017:  299
  2017/2018:  298
  2018/2019:  1642
  2019/2020:  2710
  2020/2021:  4859
  2021/2022:  6220
  2022/2023:  7862
  2023/2024:  10214
  2024/2025:  12699