league: armenia_armenian_premier_league
league_name_pretty: 'Armenian Premier League'
predictions_pathways:
  Match_Result: /root/barnard/ML/Models/armenia_armenian_premier_league/Datasets/MR_2425_Prediction_Dataset.csv
  BTTS_FTS: /root/barnard/ML/Models/armenia_armenian_premier_league/Datasets/BTTS_FTS_2425_Prediction_Dataset.csv
  Clean_Sheet: /root/barnard/ML/Models/armenia_armenian_premier_league/Datasets/CS_2425_Prediction_Dataset.csv
training_model_pathways:
  Match_Result: /root/barnard/ML/Models/armenia_armenian_premier_league/Training-Results/Match-Result
  BTTS_FTS: /root/barnard/ML/Models/armenia_armenian_premier_league/Training-Results/BTTS-FTS
  Clean_Sheet: /root/barnard/ML/Models/armenia_armenian_premier_league/Training-Results/Clean-Sheet
prediction_metrics_pathway:
  Match_Result: /root/barnard/ML/Models/armenia_armenian_premier_league/Prediction-Results/Match-Result
  BTTS_FTS: /root/barnard/ML/Models/armenia_armenian_premier_league/Prediction-Results/BTTS-FTS
  Clean_Sheet: /root/barnard/ML/Models/armenia_armenian_premier_league/Prediction-Results/Clean-Sheet
prediction_model_pathway:
  Match_Result: "/root/barnard/ML/Models/combined_leagues/Training-Results/Match-Result/v6-ionised-ect-rs42/v6-ionised-ect-rs42.joblib"
  BTTS_FTS: ''
  Clean_Sheet: ''
training_dataset_pathway:
  Match_Result: /root/barnard/ML/Models/armenia_armenian_premier_league/Datasets/MR_Dataset.csv
  BTTS_FTS: /root/barnard/ML/Models/armenia_armenian_premier_league/Datasets/BTTS_FTS_Dataset.csv
  Clean_Sheet: /root/barnard/ML/Models/armenia_armenian_premier_league/Datasets/Clean_Sheet_Dataset.csv
country: ARM
league_type: domestic
domestic_value: 1
competition_ids:
  2013/2014:  135
  2014/2015:  134
  2015/2016:  216
  2016/2017:  133
  2017/2018:  185
  2018/2019:  1671
  2019/2020:  2403
  2020/2021:  4613
  2021/2022:  6151
  2022/2023:  7863
  2023/2024:  9703
  2024/2025:  12638
