league: azerbaijan_premyer_liqas
league_name_pretty: 'Azerbaijan Premier League'
predictions_pathways:
  Match_Result: /root/barnard/ML/Models/azerbaijan_premyer_liqas/Datasets/MR_2425_Prediction_Dataset.csv
  BTTS_FTS: /root/barnard/ML/Models/azerbaijan_premyer_liqas/Datasets/BTTS_FTS_2425_Prediction_Dataset.csv
  Clean_Sheet: /root/barnard/ML/Models/azerbaijan_premyer_liqas/Datasets/CS_2425_Prediction_Dataset.csv
training_model_pathways:
  Match_Result: /root/barnard/ML/Models/azerbaijan_premyer_liqas/Training-Results/Match-Result
  BTTS_FTS: /root/barnard/ML/Models/azerbaijan_premyer_liqas/Training-Results/BTTS-FTS
  Clean_Sheet: /root/barnard/ML/Models/azerbaijan_premyer_liqas/Training-Results/Clean-Sheet
prediction_metrics_pathway:
  Match_Result: /root/barnard/ML/Models/azerbaijan_premyer_liqas/Prediction-Results/Match-Result
  BTTS_FTS: /root/barnard/ML/Models/azerbaijan_premyer_liqas/Prediction-Results/BTTS-FTS
  Clean_Sheet: /root/barnard/ML/Models/azerbaijan_premyer_liqas/Prediction-Results/Clean-Sheet
prediction_model_pathway:
  Match_Result: "/root/barnard/ML/Models/combined_leagues/Training-Results/Match-Result/v6-ionised-ect-rs42/v6-ionised-ect-rs42.joblib"
  BTTS_FTS: ''
  Clean_Sheet: ''
training_dataset_pathway:
  Match_Result: /root/barnard/ML/Models/azerbaijan_premyer_liqas/Datasets/MR_Dataset.csv
  BTTS_FTS: /root/barnard/ML/Models/azerbaijan_premyer_liqas/Datasets/BTTS_FTS_Dataset.csv
  Clean_Sheet: /root/barnard/ML/Models/azerbaijan_premyer_liqas/Datasets/Clean_Sheet_Dataset.csv
country: AZE
league_type: domestic
domestic_value: 1
competition_ids:
  2013/2014:  146
  2014/2015:  145
  2015/2016:  144
  2016/2017:  143
  2017/2018:  194
  2018/2019:  1713
  2019/2020:  2641
  2020/2021:  4754
  2021/2022:  6221
  2022/2023:  7850
  2023/2024:  9903
  2024/2025:  12740