league: croatia_prva_hnl
league_name_pretty: 'Croatian HNL'
predictions_pathways:
  Match_Result: /root/barnard/ML/Models/croatia_prva_hnl/Datasets/MR_2425_Prediction_Dataset.csv
  BTTS_FTS: /root/barnard/ML/Models/croatia_prva_hnl/Datasets/BTTS_FTS_2425_Prediction_Dataset.csv
  Clean_Sheet: /root/barnard/ML/Models/croatia_prva_hnl/Datasets/CS_2425_Prediction_Dataset.csv
training_model_pathways:
  Match_Result: /root/barnard/ML/Models/croatia_prva_hnl/Training-Results/Match-Result
  BTTS_FTS: /root/barnard/ML/Models/croatia_prva_hnl/Training-Results/BTTS-FTS
  Clean_Sheet: /root/barnard/ML/Models/croatia_prva_hnl/Training-Results/Clean-Sheet
prediction_metrics_pathway:
  Match_Result: /root/barnard/ML/Models/croatia_prva_hnl/Prediction-Results/Match-Result
  BTTS_FTS: /root/barnard/ML/Models/croatia_prva_hnl/Prediction-Results/BTTS-FTS
  Clean_Sheet: /root/barnard/ML/Models/croatia_prva_hnl/Prediction-Results/Clean-Sheet
prediction_model_pathway:
  Match_Result: "/root/barnard/ML/Models/combined_leagues/Training-Results/Match-Result/v6-ionised-ect-rs42/v6-ionised-ect-rs42.joblib"
  BTTS_FTS: ''
  Clean_Sheet: ''
training_dataset_pathway:
  Match_Result: /root/barnard/ML/Models/croatia_prva_hnl/Datasets/MR_Dataset.csv
  BTTS_FTS: /root/barnard/ML/Models/croatia_prva_hnl/Datasets/BTTS_FTS_Dataset.csv
  Clean_Sheet: /root/barnard/ML/Models/croatia_prva_hnl/Datasets/Clean_Sheet_Dataset.csv
country: HRV
league_type: domestic
domestic_value: 1
competition_ids:
  2013/2014:  404
  2014/2015:  403
  2015/2016:  402
  2016/2017:  401
  2017/2018:  397
  2018/2019:  1557
  2019/2020:  2278
  2020/2021:  4660
  2021/2022:  5956
  2022/2023:  7457
  2023/2024:  9542
  2024/2025:  12121
