league: czech_republic_first_league
league_name_pretty: 'Czech Republic First League'
predictions_pathways:
  Match_Result: /root/barnard/ML/Models/czech_republic_first_league/Datasets/MR_2425_Prediction_Dataset.csv
  BTTS_FTS: /root/barnard/ML/Models/czech_republic_first_league/Datasets/BTTS_FTS_2425_Prediction_Dataset.csv
  Clean_Sheet: /root/barnard/ML/Models/czech_republic_first_league/Datasets/CS_2425_Prediction_Dataset.csv
training_model_pathways:
  Match_Result: /root/barnard/ML/Models/czech_republic_first_league/Training-Results/Match-Result
  BTTS_FTS: /root/barnard/ML/Models/czech_republic_first_league/Training-Results/BTTS-FTS
  Clean_Sheet: /root/barnard/ML/Models/czech_republic_first_league/Training-Results/Clean-Sheet
prediction_metrics_pathway:
  Match_Result: /root/barnard/ML/Models/czech_republic_first_league/Prediction-Results/Match-Result
  BTTS_FTS: /root/barnard/ML/Models/czech_republic_first_league/Prediction-Results/BTTS-FTS
  Clean_Sheet: /root/barnard/ML/Models/czech_republic_first_league/Prediction-Results/Clean-Sheet
prediction_model_pathway:
  Match_Result: "/root/barnard/ML/Models/combined_leagues/Training-Results/Match-Result/v6-ionised-ect-rs42/v6-ionised-ect-rs42.joblib"
  BTTS_FTS: ''
  Clean_Sheet: ''
training_dataset_pathway:
  Match_Result: /root/barnard/ML/Models/czech_republic_first_league/Datasets/MR_Dataset.csv
  BTTS_FTS: /root/barnard/ML/Models/czech_republic_first_league/Datasets/BTTS_FTS_Dataset.csv
  Clean_Sheet: /root/barnard/ML/Models/czech_republic_first_league/Datasets/Clean_Sheet_Dataset.csv
country: CZE
league_type: domestic
domestic_value: 1
competition_ids:
  2011/2012:  4314
  2012/2013:  4308
  2013/2014:  541
  2014/2015:  540
  2015/2016:  539
  2016/2017:  538
  2017/2018:  537
  2018/2019:  1545
  2019/2020:  2268
  2020/2021:  4801
  2021/2022:  5938
  2022/2023:  7586
  2023/2024:  9592
  2024/2025:  12336
