league: england_premier_league
league_name_pretty: 'English Premier League'
predictions_pathways:
  Match_Result: /root/barnard/ML/Models/england_premier_league/Datasets/MR_2425_Prediction_Dataset.csv
  BTTS_FTS: /root/barnard/ML/Models/england_premier_league/Datasets/BTTS_FTS_2425_Prediction_Dataset.csv
  Clean_Sheet: /root/barnard/ML/Models/england_premier_league/Datasets/CS_2425_Prediction_Dataset.csv
training_model_pathways:
  Match_Result: /root/barnard/ML/Models/england_premier_league/Training-Results/Match-Result
  BTTS_FTS: /root/barnard/ML/Models/england_premier_league/Training-Results/BTTS-FTS
  Clean_Sheet: /root/barnard/ML/Models/england_premier_league/Training-Results/Clean-Sheet
prediction_metrics_pathway:
  Match_Result: /root/barnard/ML/Models/england_premier_league/Prediction-Results/Match-Result
  BTTS_FTS: /root/barnard/ML/Models/england_premier_league/Prediction-Results/BTTS-FTS
  Clean_Sheet: /root/barnard/ML/Models/england_premier_league/Prediction-Results/Clean-Sheet
prediction_model_pathway:
  Match_Result:   "/root/barnard/ML/Models/combined_leagues/Training-Results/Match-Result/v6-pushful-halma-rs22/v6-pushful-halma-rs22.joblib"
  BTTS_FTS: ''
  Clean_Sheet: ''
training_dataset_pathway:
  Match_Result: /root/barnard/ML/Models/england_premier_league/Datasets/MR_Dataset.csv
  BTTS_FTS: /root/barnard/ML/Models/england_premier_league/Datasets/BTTS_FTS_Dataset.csv
  Clean_Sheet: /root/barnard/ML/Models/england_premier_league/Datasets/Clean_Sheet_Dataset.csv 
country: UNK
league_type: domestic
domestic_value: 1
competition_ids:
  2011/2012:  3119
  2012/2013:  246
  2013/2014:  12
  2014/2015:  11
  2015/2016:  10
  2016/2017:  9
  2017/2018:  161
  2018/2019:  1625
  2019/2020:  2012
  2020/2021:  4759
  2021/2022:  6135
  2022/2023:  7704
  2023/2024:  9660
  2024/2025:  12325
