league: england_championship
league_name_pretty: 'England EFL Championship'
predictions_pathways:
  Match_Result: /root/barnard/ML/Models/england_championship/Datasets/MR_2425_Prediction_Dataset.csv
  BTTS_FTS: /root/barnard/ML/Models/england_championship/Datasets/BTTS_FTS_2425_Prediction_Dataset.csv
  Clean_Sheet: /root/barnard/ML/Models/england_championship/Datasets/CS_2425_Prediction_Dataset.csv
training_model_pathways:
  Match_Result: /root/barnard/ML/Models/england_championship/Training-Results/Match-Result
  BTTS_FTS: /root/barnard/ML/Models/england_championship/Training-Results/BTTS-FTS
  Clean_Sheet: /root/barnard/ML/Models/england_championship/Training-Results/Clean-Sheet
prediction_metrics_pathway:
  Match_Result: /root/barnard/ML/Models/england_championship/Prediction-Results/Match-Result
  BTTS_FTS: /root/barnard/ML/Models/england_championship/Prediction-Results/BTTS-FTS
  Clean_Sheet: /root/barnard/ML/Models/england_championship/Prediction-Results/Clean-Sheet
prediction_model_pathway:
  Match_Result: "/root/barnard/ML/Models/combined_leagues/Training-Results/Match-Result/v6-ionised-ect-rs42/v6-ionised-ect-rs42.joblib"
  BTTS_FTS: ''
  Clean_Sheet: ''
training_dataset_pathway:
  Match_Result: /root/barnard/ML/Models/england_championship/Datasets/MR_Dataset.csv
  BTTS_FTS: /root/barnard/ML/Models/england_championship/Datasets/BTTS_FTS_Dataset.csv
  Clean_Sheet: /root/barnard/ML/Models/england_championship/Datasets/Clean_Sheet_Dataset.csv
country: UNK
league_type: domestic
domestic_value: 2
competition_ids:
  2011/2012:  3143
  2012/2013:  3141
  2013/2014:  27
  2014/2015:  26
  2015/2016:  25
  2016/2017:  22
  2017/2018:  165
  2018/2019:  1624
  2019/2020:  2187
  2020/2021:  4912
  2021/2022:  6089
  2022/2023:  7593
  2023/2024:  9663
  2024/2025:  12451
