league: estonia_meistriliiga
league_name_pretty: 'Estonian Meistriliiga'
predictions_pathways:
  Match_Result: /root/barnard/ML/Models/estonia_meistriliiga/Datasets/MR_2425_Prediction_Dataset.csv
  BTTS_FTS: /root/barnard/ML/Models/estonia_meistriliiga/Datasets/BTTS_FTS_2425_Prediction_Dataset.csv
  Clean_Sheet: /root/barnard/ML/Models/estonia_meistriliiga/Datasets/CS_2425_Prediction_Dataset.csv
training_model_pathways:
  Match_Result: /root/barnard/ML/Models/estonia_meistriliiga/Training-Results/Match-Result
  BTTS_FTS: /root/barnard/ML/Models/estonia_meistriliiga/Training-Results/BTTS-FTS
  Clean_Sheet: /root/barnard/ML/Models/estonia_meistriliiga/Training-Results/Clean-Sheet
prediction_metrics_pathway:
  Match_Result: /root/barnard/ML/Models/estonia_meistriliiga/Prediction-Results/Match-Result
  BTTS_FTS: /root/barnard/ML/Models/estonia_meistriliiga/Prediction-Results/BTTS-FTS
  Clean_Sheet: /root/barnard/ML/Models/estonia_meistriliiga/Prediction-Results/Clean-Sheet
prediction_model_pathway:
  Match_Result: "/root/barnard/ML/Models/combined_leagues/Training-Results/Match-Result/v6-ionised-ect-rs42/v6-ionised-ect-rs42.joblib"
  BTTS_FTS: ''
  Clean_Sheet: ''
training_dataset_pathway:
  Match_Result: /root/barnard/ML/Models/estonia_meistriliiga/Datasets/MR_Dataset.csv
  BTTS_FTS: /root/barnard/ML/Models/estonia_meistriliiga/Datasets/BTTS_FTS_Dataset.csv
  Clean_Sheet: /root/barnard/ML/Models/estonia_meistriliiga/Datasets/Clean_Sheet_Dataset.csv
country: EST
league_type: domestic
domestic_value: 1
competition_ids:
  2013/2014:  349
  2014/2015:  348
  2015/2016:  347
  2016/2017:  346
  2017/2018:  345
  2018/2019:  988
  2019/2020:  1882
  2020/2021:  3675
  2021/2022:  5472
  2022/2023:  7073
  2023/2024:  8898
  2024/2025:  11119
