league: europe_uefa_europa_league
predictions_pathways:
  Match_Result: /root/barnard/ML/Models/europe_uefa_europa_league/Datasets/MR_2425_Prediction_Dataset.csv
  BTTS_FTS: /root/barnard/ML/Models/europe_uefa_europa_league/Datasets/BTTS_FTS_2425_Prediction_Dataset.csv
  Clean_Sheet: /root/barnard/ML/Models/europe_uefa_europa_league/Datasets/CS_2425_Prediction_Dataset.csv
training_model_pathways:
  Match_Result: /root/barnard/ML/Models/europe_uefa_europa_league/Training-Results/Match-Result
  BTTS_FTS: /root/barnard/ML/Models/europe_uefa_europa_league/Training-Results/BTTS-FTS
  Clean_Sheet: /root/barnard/ML/Models/europe_uefa_europa_league/Training-Results/Clean-Sheet
prediction_metrics_pathway:
  Match_Result: /root/barnard/ML/Models/europe_uefa_europa_league/Prediction-Results/Match-Result
  BTTS_FTS: /root/barnard/ML/Models/europe_uefa_europa_league/Prediction-Results/BTTS-FTS
  Clean_Sheet: /root/barnard/ML/Models/europe_uefa_europa_league/Prediction-Results/Clean-Sheet
prediction_model_pathway:
  Match_Result: ''
  BTTS_FTS: ''
  Clean_Sheet: ''
training_dataset_pathway:
  Match_Result: /root/barnard/ML/Models/europe_uefa_europa_league/Datasets/MR_Dataset.csv
  BTTS_FTS: /root/barnard/ML/Models/europe_uefa_europa_league/Datasets/BTTS_FTS_Dataset.csv
  Clean_Sheet: /root/barnard/ML/Models/europe_uefa_europa_league/Datasets/Clean_Sheet_Dataset.csv
country: EUR
league_type: interleague
domestic_value: 1
competition_ids:
  2011/2012:  4070
  2012/2013:  4060
  2013/2014:  1806
  2014/2015:  1805
  2015/2016:  6731
  2016/2017:  1700
  2017/2018:  964
  2018/2019:  1535
  2019/2020:  2203
  2020/2021:  4693
  2021/2022:  6218
  2022/2023:  7985
  2023/2024:  10210
  2024/2025:  12327
