league: europe_uefa_champions_league
predictions_pathways:
  Match_Result: /root/barnard/ML/Models/europe_uefa_champions_league/Datasets/MR_2425_Prediction_Dataset.csv
  BTTS_FTS: /root/barnard/ML/Models/europe_uefa_champions_league/Datasets/BTTS_FTS_2425_Prediction_Dataset.csv
  Clean_Sheet: /root/barnard/ML/Models/europe_uefa_champions_league/Datasets/CS_2425_Prediction_Dataset.csv
training_model_pathways:
  Match_Result: /root/barnard/ML/Models/europe_uefa_champions_league/Training-Results/Match-Result
  BTTS_FTS: /root/barnard/ML/Models/europe_uefa_champions_league/Training-Results/BTTS-FTS
  Clean_Sheet: /root/barnard/ML/Models/europe_uefa_champions_league/Training-Results/Clean-Sheet
prediction_metrics_pathway:
  Match_Result: /root/barnard/ML/Models/europe_uefa_champions_league/Prediction-Results/Match-Result
  BTTS_FTS: /root/barnard/ML/Models/europe_uefa_champions_league/Prediction-Results/BTTS-FTS
  Clean_Sheet: /root/barnard/ML/Models/europe_uefa_champions_league/Prediction-Results/Clean-Sheet
prediction_model_pathway:
  Match_Result: "/root/barnard/ML/Models/combined_leagues/Training-Results/Match-Result/v6-ionised-ect-rs42/v6-ionised-ect-rs42.joblib"
  BTTS_FTS: ''
  Clean_Sheet: ''
training_dataset_pathway:
  Match_Result: /root/barnard/ML/Models/europe_uefa_champions_league/Datasets/MR_Dataset.csv
  BTTS_FTS: /root/barnard/ML/Models/europe_uefa_champions_league/Datasets/BTTS_FTS_Dataset.csv
  Clean_Sheet: /root/barnard/ML/Models/europe_uefa_champions_league/Datasets/Clean_Sheet_Dataset.csv
country: EUR
league_type: interleague
domestic_value: 1
competition_ids:
  2011/2012:  4062
  2012/2013:  4053
  2013/2014:  159
  2014/2015:  158
  2015/2016:  157
  2016/2017:  6
  2017/2018:  247
  2018/2019:  1534
  2019/2020:  2202
  2020/2021:  4655
  2021/2022:  5977
  2022/2023:  7455
  2023/2024:  9543
  2024/2025:  12321
