league: france_ligue_1
league_name_pretty: 'French Ligue 1'
predictions_pathways:
  Match_Result: /root/barnard/ML/Models/france_ligue_1/Datasets/MR_2425_Prediction_Dataset.csv
  BTTS_FTS: /root/barnard/ML/Models/france_ligue_1/Datasets/BTTS_FTS_2425_Prediction_Dataset.csv
  Clean_Sheet: /root/barnard/ML/Models/france_ligue_1/Datasets/CS_2425_Prediction_Dataset.csv
training_model_pathways:
  Match_Result: /root/barnard/ML/Models/france_ligue_1/Training-Results/Match-Result
  BTTS_FTS: /root/barnard/ML/Models/france_ligue_1/Training-Results/BTTS-FTS
  Clean_Sheet: /root/barnard/ML/Models/france_ligue_1/Training-Results/Clean-Sheet
prediction_metrics_pathway:
  Match_Result: /root/barnard/ML/Models/france_ligue_1/Prediction-Results/Match-Result
  BTTS_FTS: /root/barnard/ML/Models/france_ligue_1/Prediction-Results/BTTS-FTS
  Clean_Sheet: /root/barnard/ML/Models/france_ligue_1/Prediction-Results/Clean-Sheet 
prediction_model_pathway:
  Match_Result: "/root/barnard/ML/Models/combined_leagues/Training-Results/Match-Result/v6-ionised-ect-rs42/v6-ionised-ect-rs42.joblib"
  BTTS_FTS: ''
  Clean_Sheet: ''
training_dataset_pathway:
  Match_Result: /root/barnard/ML/Models/france_ligue_1/Datasets/MR_Dataset.csv
  BTTS_FTS: /root/barnard/ML/Models/france_ligue_1/Datasets/BTTS_FTS_Dataset.csv
  Clean_Sheet: /root/barnard/ML/Models/france_ligue_1/Datasets/Clean_Sheet_Dataset.csv
country: FRA
league_type: domestic
domestic_value: 1
competition_ids:
  2011/2012:  4136
  2012/2013:  4127
  2013/2014:  67
  2014/2015:  66
  2015/2016:  75
  2016/2017:  65
  2017/2018:  180
  2018/2019:  1508
  2019/2020:  2392
  2020/2021:  4505
  2021/2022:  6019
  2022/2023:  7500
  2023/2024:  9674
  2024/2025:  12337
