league: germany_2_bundesliga
league_name_pretty: 'German Bundesliga 2'
predictions_pathways:
  Match_Result: /root/barnard/ML/Models/germany_2_bundesliga/Datasets/MR_2425_Prediction_Dataset.csv
  BTTS_FTS: /root/barnard/ML/Models/germany_2_bundesliga/Datasets/BTTS_FTS_2425_Prediction_Dataset.csv
  Clean_Sheet: /root/barnard/ML/Models/germany_2_bundesliga/Datasets/CS_2425_Prediction_Dataset.csv
training_model_pathways:
  Match_Result: /root/barnard/ML/Models/germany_2_bundesliga/Training-Results/Match-Result
  BTTS_FTS: /root/barnard/ML/Models/germany_2_bundesliga/Training-Results/BTTS-FTS
  Clean_Sheet: /root/barnard/ML/Models/germany_2_bundesliga/Training-Results/Clean-Sheet
prediction_metrics_pathway:
  Match_Result: /root/barnard/ML/Models/germany_2_bundesliga/Prediction-Results/Match-Result
  BTTS_FTS: /root/barnard/ML/Models/germany_2_bundesliga/Prediction-Results/BTTS-FTS
  Clean_Sheet: /root/barnard/ML/Models/germany_2_bundesliga/Prediction-Results/Clean-Sheet
prediction_model_pathway:
  Match_Result: "/root/barnard/ML/Models/combined_leagues/Training-Results/Match-Result/v6-ionised-ect-rs42/v6-ionised-ect-rs42.joblib"
  BTTS_FTS: ''
  Clean_Sheet: ''
training_dataset_pathway:
  Match_Result: /root/barnard/ML/Models/germany_2_bundesliga/Datasets/MR_Dataset.csv
  BTTS_FTS: /root/barnard/ML/Models/germany_2_bundesliga/Datasets/BTTS_FTS_Dataset.csv
  Clean_Sheet: /root/barnard/ML/Models/germany_2_bundesliga/Datasets/Clean_Sheet_Dataset.csv
country: DEU
league_type: domestic
domestic_value: 2
competition_ids:
  2011/2012:  4195
  2012/2013:  4168
  2013/2014:  4131
  2014/2015:  85
  2015/2016:  84
  2016/2017:  83
  2017/2018:  188
  2018/2019:  1578
  2019/2020:  4388
  2020/2021:  4676
  2021/2022:  6020
  2022/2023:  7499
  2023/2024:  9656
  2024/2025:  12528