league: greece_super_league
league_name_pretty: 'Greek Super League'
predictions_pathways:
  Match_Result: /root/barnard/ML/Models/greece_super_league/Datasets/MR_2425_Prediction_Dataset.csv
  BTTS_FTS: /root/barnard/ML/Models/greece_super_league/Datasets/BTTS_FTS_2425_Prediction_Dataset.csv
  Clean_Sheet: /root/barnard/ML/Models/greece_super_league/Datasets/CS_2425_Prediction_Dataset.csv
training_model_pathways:
  Match_Result: /root/barnard/ML/Models/greece_super_league/Training-Results/Match-Result
  BTTS_FTS: /root/barnard/ML/Models/greece_super_league/Training-Results/BTTS-FTS
  Clean_Sheet: /root/barnard/ML/Models/greece_super_league/Training-Results/Clean-Sheet
prediction_metrics_pathway:
  Match_Result: /root/barnard/ML/Models/greece_super_league/Prediction-Results/Match-Result
  BTTS_FTS: /root/barnard/ML/Models/greece_super_league/Prediction-Results/BTTS-FTS
  Clean_Sheet: /root/barnard/ML/Models/greece_super_league/Prediction-Results/Clean-Sheet
prediction_model_pathway:
  Match_Result: "/root/barnard/ML/Models/combined_leagues/Training-Results/Match-Result/v6-ionised-ect-rs42/v6-ionised-ect-rs42.joblib"
  BTTS_FTS: ''
  Clean_Sheet: ''
training_dataset_pathway:
  Match_Result: /root/barnard/ML/Models/greece_super_league/Datasets/MR_Dataset.csv
  BTTS_FTS: /root/barnard/ML/Models/greece_super_league/Datasets/BTTS_FTS_Dataset.csv
  Clean_Sheet: /root/barnard/ML/Models/greece_super_league/Datasets/Clean_Sheet_Dataset.csv
country: GRC
league_type: domestic
domestic_value: 1
competition_ids:
  2013/2014:  934
  2014/2015:  933
  2015/2016:  209
  2016/2017:  208
  2017/2018:  207
  2018/2019:  1752
  2019/2020:  2667
  2020/2021:  4957
  2021/2022:  6282
  2022/2023:  7954
  2023/2024:  9889
  2024/2025:  12734
