league: italy_serie_a
league_name_pretty: 'Italian Serie A'
predictions_pathways:
  Match_Result: /root/barnard/ML/Models/italy_serie_a/Datasets/MR_2425_Prediction_Dataset.csv
  BTTS_FTS: /root/barnard/ML/Models/italy_serie_a/Datasets/BTTS_FTS_2425_Prediction_Dataset.csv
  Clean_Sheet: /root/barnard/ML/Models/italy_serie_a/Datasets/CS_2425_Prediction_Dataset.csv
training_model_pathways:
  Match_Result: /root/barnard/ML/Models/italy_serie_a/Training-Results/Match-Result
  BTTS_FTS: /root/barnard/ML/Models/italy_serie_a/Training-Results/BTTS-FTS
  Clean_Sheet: /root/barnard/ML/Models/italy_serie_a/Training-Results/Clean-Sheet
prediction_metrics_pathway:
  Match_Result: /root/barnard/ML/Models/italy_serie_a/Prediction-Results/Match-Result
  BTTS_FTS: /root/barnard/ML/Models/italy_serie_a/Prediction-Results/BTTS-FTS
  Clean_Sheet: /root/barnard/ML/Models/italy_serie_a/Prediction-Results/Clean-Sheet
prediction_model_pathway:
  Match_Result: "/root/barnard/ML/Models/combined_leagues/Training-Results/Match-Result/v6-ionised-ect-rs42/v6-ionised-ect-rs42.joblib"
  BTTS_FTS: ''
  Clean_Sheet: ''
training_dataset_pathway:
  Match_Result: /root/barnard/ML/Models/italy_serie_a/Datasets/MR_Dataset.csv
  BTTS_FTS: /root/barnard/ML/Models/italy_serie_a/Datasets/BTTS_FTS_Dataset.csv
  Clean_Sheet: /root/barnard/ML/Models/italy_serie_a/Datasets/Clean_Sheet_Dataset.csv
country: ITA
league_type: domestic
domestic_value: 1
competition_ids:
  2011/2012:  3940
  2012/2013:  3945
  2013/2014:  71
  2014/2015:  70
  2015/2016:  69
  2016/2017:  68
  2017/2018:  182
  2018/2019:  1680
  2019/2020:  2588
  2020/2021:  4889
  2021/2022:  6198
  2022/2023:  7608
  2023/2024:  9697
  2024/2025:  12530