league: italy_serie_b
league_name_pretty: 'Italian Serie B'
predictions_pathways:
  Match_Result: /root/barnard/ML/Models/italy_serie_b/Datasets/MR_2425_Prediction_Dataset.csv
  BTTS_FTS: /root/barnard/ML/Models/italy_serie_b/Datasets/BTTS_FTS_2425_Prediction_Dataset.csv
  Clean_Sheet: /root/barnard/ML/Models/italy_serie_b/Datasets/CS_2425_Prediction_Dataset.csv
training_model_pathways:
  Match_Result: /root/barnard/ML/Models/italy_serie_b/Training-Results/Match-Result
  BTTS_FTS: /root/barnard/ML/Models/italy_serie_b/Training-Results/BTTS-FTS
  Clean_Sheet: /root/barnard/ML/Models/italy_serie_b/Training-Results/Clean-Sheet
prediction_metrics_pathway:
  Match_Result: /root/barnard/ML/Models/italy_serie_b/Prediction-Results/Match-Result
  BTTS_FTS: /root/barnard/ML/Models/italy_serie_b/Prediction-Results/BTTS-FTS
  Clean_Sheet: /root/barnard/ML/Models/italy_serie_b/Prediction-Results/Clean-Sheet
prediction_model_pathway:
  Match_Result: "/root/barnard/ML/Models/combined_leagues/Training-Results/Match-Result/v6-ionised-ect-rs42/v6-ionised-ect-rs42.joblib"
  BTTS_FTS: ''
  Clean_Sheet: ''
training_dataset_pathway:
  Match_Result: /root/barnard/ML/Models/italy_serie_b/Datasets/MR_Dataset.csv
  BTTS_FTS: /root/barnard/ML/Models/italy_serie_b/Datasets/BTTS_FTS_Dataset.csv
  Clean_Sheet: /root/barnard/ML/Models/italy_serie_b/Datasets/Clean_Sheet_Dataset.csv
country: ITA
league_type: domestic
domestic_value: 2
competition_ids:
  2011/2012:  3949
  2012/2013:  81
  2013/2014:  80
  2014/2015:  79
  2015/2016:  78
  2016/2017:  77
  2017/2018:  183
  2018/2019:  1749
  2019/2020:  2642
  2020/2021:  4972
  2021/2022:  6205
  2022/2023:  7864
  2023/2024:  9808
  2024/2025:  12621