league: netherlands_eredivisie
league_name_pretty: 'Dutch Eredivisie'
predictions_pathways:
  Match_Result: /root/barnard/ML/Models/netherlands_eredivisie/Datasets/MR_2425_Prediction_Dataset.csv
  BTTS_FTS: /root/barnard/ML/Models/netherlands_eredivisie/Datasets/BTTS_FTS_2425_Prediction_Dataset.csv
  Clean_Sheet: /root/barnard/ML/Models/netherlands_eredivisie/Datasets/CS_2425_Prediction_Dataset.csv
training_model_pathways:
  Match_Result: /root/barnard/ML/Models/netherlands_eredivisie/Training-Results/Match-Result
  BTTS_FTS: /root/barnard/ML/Models/netherlands_eredivisie/Training-Results/BTTS-FTS
  Clean_Sheet: /root/barnard/ML/Models/netherlands_eredivisie/Training-Results/Clean-Sheet
prediction_metrics_pathway:
  Match_Result: /root/barnard/ML/Models/netherlands_eredivisie/Prediction-Results/Match-Result
  BTTS_FTS: /root/barnard/ML/Models/netherlands_eredivisie/Prediction-Results/BTTS-FTS
  Clean_Sheet: /root/barnard/ML/Models/netherlands_eredivisie/Prediction-Results/Clean-Sheet
prediction_model_pathway:
  Match_Result: "/root/barnard/ML/Models/combined_leagues/Training-Results/Match-Result/v6-ionised-ect-rs42/v6-ionised-ect-rs42.joblib"
  BTTS_FTS: ''
  Clean_Sheet: ''
training_dataset_pathway:
  Match_Result: /root/barnard/ML/Models/netherlands_eredivisie/Datasets/MR_Dataset.csv
  BTTS_FTS: /root/barnard/ML/Models/netherlands_eredivisie/Datasets/BTTS_FTS_Dataset.csv
  Clean_Sheet: /root/barnard/ML/Models/netherlands_eredivisie/Datasets/Clean_Sheet_Dataset.csv
country: NLD
league_type: domestic
domestic_value: 1
competition_ids:
  2011/2012:  4234
  2012/2013:  4226
  2013/2014:  54
  2014/2015:  53
  2015/2016:  52
  2016/2017:  51
  2017/2018:  178
  2018/2019:  1585
  2019/2020:  2272
  2020/2021:  4746
  2021/2022:  5951
  2022/2023:  7482
  2023/2024:  9653
  2024/2025:  12322
