league: portugal_liga_nos
league_name_pretty: 'Portugese Liga Nos'
predictions_pathways:
  Match_Result: /root/barnard/ML/Models/portugal_liga_nos/Datasets/MR_2425_Prediction_Dataset.csv
  BTTS_FTS: /root/barnard/ML/Models/portugal_liga_nos/Datasets/BTTS_FTS_2425_Prediction_Dataset.csv
  Clean_Sheet: /root/barnard/ML/Models/portugal_liga_nos/Datasets/CS_2425_Prediction_Dataset.csv
training_model_pathways:
  Match_Result: /root/barnard/ML/Models/portugal_liga_nos/Training-Results/Match-Result
  BTTS_FTS: /root/barnard/ML/Models/portugal_liga_nos/Training-Results/BTTS-FTS
  Clean_Sheet: /root/barnard/ML/Models/portugal_liga_nos/Training-Results/Clean-Sheet
prediction_metrics_pathway:
  Match_Result: /root/barnard/ML/Models/portugal_liga_nos/Prediction-Results/Match-Result
  BTTS_FTS: /root/barnard/ML/Models/portugal_liga_nos/Prediction-Results/BTTS-FTS
  Clean_Sheet: /root/barnard/ML/Models/portugal_liga_nos/Prediction-Results/Clean-Sheet
prediction_model_pathway:
  Match_Result: "/root/barnard/ML/Models/combined_leagues/Training-Results/Match-Result/v6-ionised-ect-rs42/v6-ionised-ect-rs42.joblib"
  BTTS_FTS: ''
  Clean_Sheet: ''
training_dataset_pathway:
  Match_Result: /root/barnard/ML/Models/portugal_liga_nos/Datasets/MR_Dataset.csv
  BTTS_FTS: /root/barnard/ML/Models/portugal_liga_nos/Datasets/BTTS_FTS_Dataset.csv
  Clean_Sheet: /root/barnard/ML/Models/portugal_liga_nos/Datasets/Clean_Sheet_Dataset.csv
country: PRT
league_type: domestic
domestic_value: 1
competition_ids:
  2011/2012:  4232
  2012/2013:  4225
  2013/2014:  18
  2014/2015:  17
  2015/2016:  14
  2016/2017:  13
  2017/2018:  173
  2018/2019:  1593
  2019/2020:  2321
  2020/2021:  4885
  2021/2022:  6117
  2022/2023:  7731
  2023/2024:  9984
  2024/2025:  12931