league: portugal_liga_pro
league_name_pretty: 'Portugese Liga Pro'
predictions_pathways:
  Match_Result: /root/barnard/ML/Models/portugal_liga_pro/Datasets/MR_2425_Prediction_Dataset.csv
  BTTS_FTS: /root/barnard/ML/Models/portugal_liga_pro/Datasets/BTTS_FTS_2425_Prediction_Dataset.csv
  Clean_Sheet: /root/barnard/ML/Models/portugal_liga_pro/Datasets/CS_2425_Prediction_Dataset.csv
training_model_pathways:
  Match_Result: /root/barnard/ML/Models/portugal_liga_pro/Training-Results/Match-Result
  BTTS_FTS: /root/barnard/ML/Models/portugal_liga_pro/Training-Results/BTTS-FTS
  Clean_Sheet: /root/barnard/ML/Models/portugal_liga_pro/Training-Results/Clean-Sheet
prediction_metrics_pathway:
  Match_Result: /root/barnard/ML/Models/portugal_liga_pro/Prediction-Results/Match-Result
  BTTS_FTS: /root/barnard/ML/Models/portugal_liga_pro/Prediction-Results/BTTS-FTS
  Clean_Sheet: /root/barnard/ML/Models/portugal_liga_pro/Prediction-Results/Clean-Sheet
prediction_model_pathway:
  Match_Result: "/root/barnard/ML/Models/combined_leagues/Training-Results/Match-Result/v6-ionised-ect-rs42/v6-ionised-ect-rs42.joblib"
  BTTS_FTS: ''
  Clean_Sheet: ''
training_dataset_pathway:
  Match_Result: /root/barnard/ML/Models/portugal_liga_pro/Datasets/MR_Dataset.csv
  BTTS_FTS: /root/barnard/ML/Models/portugal_liga_pro/Datasets/BTTS_FTS_Dataset.csv
  Clean_Sheet: /root/barnard/ML/Models/portugal_liga_pro/Datasets/Clean_Sheet_Dataset.csv
country: PRT
league_type: domestic
domestic_value: 2
competition_ids:
  2012/2013:  4291
  2014/2015:  4284
  2015/2016:  966
  2016/2017:  965
  2017/2018:  174
  2018/2019:  1594
  2019/2020:  2320
  2020/2021:  4886
  2021/2022:  6116
  2022/2023:  7732
  2023/2024:  9704
  2024/2025:  12585
