league: romania_liga_i
league_name_pretty: 'Romanian Liga 1'
predictions_pathways:
  Match_Result: /root/barnard/ML/Models/romania_liga_i/Datasets/MR_2425_Prediction_Dataset.csv
  BTTS_FTS: /root/barnard/ML/Models/romania_liga_i/Datasets/BTTS_FTS_2425_Prediction_Dataset.csv
  Clean_Sheet: /root/barnard/ML/Models/romania_liga_i/Datasets/CS_2425_Prediction_Dataset.csv
training_model_pathways:
  Match_Result: /root/barnard/ML/Models/romania_liga_i/Training-Results/Match-Result
  BTTS_FTS: /root/barnard/ML/Models/romania_liga_i/Training-Results/BTTS-FTS
  Clean_Sheet: /root/barnard/ML/Models/romania_liga_i/Training-Results/Clean-Sheet
prediction_metrics_pathway:
  Match_Result: /root/barnard/ML/Models/romania_liga_i/Prediction-Results/Match-Result
  BTTS_FTS: /root/barnard/ML/Models/romania_liga_i/Prediction-Results/BTTS-FTS
  Clean_Sheet: /root/barnard/ML/Models/romania_liga_i/Prediction-Results/Clean-Sheet
prediction_model_pathway:
  Match_Result: "/root/barnard/ML/Models/combined_leagues/Training-Results/Match-Result/v6-ionised-ect-rs42/v6-ionised-ect-rs42.joblib"
  BTTS_FTS: ''
  Clean_Sheet: ''
training_dataset_pathway:
  Match_Result: /root/barnard/ML/Models/romania_liga_i/Datasets/MR_Dataset.csv
  BTTS_FTS: /root/barnard/ML/Models/romania_liga_i/Datasets/BTTS_FTS_Dataset.csv
  Clean_Sheet: /root/barnard/ML/Models/romania_liga_i/Datasets/Clean_Sheet_Dataset.csv
country: ROU
league_type: domestic
domestic_value: 1
competition_ids:
  2013/2014:  1090
  2014/2015:  1089
  2015/2016:  1088
  2016/2017:  1087
  2017/2018:  1086
  2018/2019:  1596
  2019/2020:  2312
  2020/2021:  4764
  2021/2022:  6037
  2022/2023:  7663
  2023/2024:  9622
  2024/2025:  12495
