league: spain_la_liga
league_name_pretty: 'Spanish La Liga'
predictions_pathways:
  Match_Result: /root/barnard/ML/Models/spain_la_liga/Datasets/MR_2425_Prediction_Dataset.csv
  BTTS_FTS: /root/barnard/ML/Models/spain_la_liga/Datasets/BTTS_FTS_2425_Prediction_Dataset.csv
  Clean_Sheet: /root/barnard/ML/Models/spain_la_liga/Datasets/CS_2425_Prediction_Dataset.csv
training_model_pathways:
  Match_Result: /root/barnard/ML/Models/spain_la_liga/Training-Results/Match-Result
  BTTS_FTS: /root/barnard/ML/Models/spain_la_liga/Training-Results/BTTS-FTS
  Clean_Sheet: /root/barnard/ML/Models/spain_la_liga/Training-Results/Clean-Sheet
prediction_metrics_pathway:
  Match_Result: /root/barnard/ML/Models/spain_la_liga/Prediction-Results/Match-Result
  BTTS_FTS: /root/barnard/ML/Models/spain_la_liga/Prediction-Results/BTTS-FTS
  Clean_Sheet: /root/barnard/ML/Models/spain_la_liga/Prediction-Results/Clean-Sheet
prediction_model_pathway:
  Match_Result: "/root/barnard/ML/Models/combined_leagues/Training-Results/Match-Result/v6-ionised-ect-rs42/v6-ionised-ect-rs42.joblib"
  BTTS_FTS: ''
  Clean_Sheet: ''
training_dataset_pathway:
  Match_Result: /root/barnard/ML/Models/spain_la_liga/Datasets/MR_Dataset.csv
  BTTS_FTS: /root/barnard/ML/Models/spain_la_liga/Datasets/BTTS_FTS_Dataset.csv
  Clean_Sheet: /root/barnard/ML/Models/spain_la_liga/Datasets/Clean_Sheet_Dataset.csv
country: ESP
league_type: domestic
domestic_value: 1
competition_ids:
  2011/2012:  3631
  2012/2013:  38
  2013/2014:  37
  2014/2015:  36
  2015/2016:  35
  2016/2017:  34
  2017/2018:  171
  2018/2019:  1677
  2019/2020:  2319
  2020/2021:  4944
  2021/2022:  6211
  2022/2023:  7665
  2023/2024:  9665
  2024/2025:  12316
