league: switzerland_super_league
league_name_pretty: 'Swiss Super League'
predictions_pathways:
  Match_Result: /root/barnard/ML/Models/switzerland_super_league/Datasets/MR_2425_Prediction_Dataset.csv
  BTTS_FTS: /root/barnard/ML/Models/switzerland_super_league/Datasets/BTTS_FTS_2425_Prediction_Dataset.csv
  Clean_Sheet: /root/barnard/ML/Models/switzerland_super_league/Datasets/CS_2425_Prediction_Dataset.csv
training_model_pathways:
  Match_Result: /root/barnard/ML/Models/switzerland_super_league/Training-Results/Match-Result
  BTTS_FTS: /root/barnard/ML/Models/switzerland_super_league/Training-Results/BTTS-FTS
  Clean_Sheet: /root/barnard/ML/Models/switzerland_super_league/Training-Results/Clean-Sheet
prediction_metrics_pathway:
  Match_Result: /root/barnard/ML/Models/switzerland_super_league/Prediction-Results/Match-Result
  BTTS_FTS: /root/barnard/ML/Models/switzerland_super_league/Prediction-Results/BTTS-FTS
  Clean_Sheet: /root/barnard/ML/Models/switzerland_super_league/Prediction-Results/Clean-Sheet
prediction_model_pathway:
  Match_Result: "/root/barnard/ML/Models/combined_leagues/Training-Results/Match-Result/v6-ionised-ect-rs42/v6-ionised-ect-rs42.joblib"
  BTTS_FTS: ''
  Clean_Sheet: ''
training_dataset_pathway:
  Match_Result: /root/barnard/ML/Models/switzerland_super_league/Datasets/MR_Dataset.csv
  BTTS_FTS: /root/barnard/ML/Models/switzerland_super_league/Datasets/BTTS_FTS_Dataset.csv
  Clean_Sheet: /root/barnard/ML/Models/switzerland_super_league/Datasets/Clean_Sheet_Dataset.csv
country: SWI
league_type: domestic
domestic_value: 1
competition_ids:
  2012/2013:  140
  2013/2014:  139
  2014/2015:  138
  2015/2016:  137
  2016/2017:  136
  2017/2018:  186
  2018/2019:  1610
  2019/2020:  2249
  2020/2021:  4906
  2021/2022:  6044
  2022/2023:  7504
  2023/2024:  9580
  2024/2025:  12326
